// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uposcashdrawer.proto

#ifndef PROTOBUF_uposcashdrawer_2eproto__INCLUDED
#define PROTOBUF_uposcashdrawer_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace JposcashdrawerZMQ {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_uposcashdrawer_2eproto();
void protobuf_AssignDesc_uposcashdrawer_2eproto();
void protobuf_ShutdownFile_uposcashdrawer_2eproto();

class Params;

enum CmdTypeCashDrawer {
  UPOSlibInit = 0,
  UPOSlibExit = 1,
  UPOSlibOpen = 2,
  UPOSlibClose = 3,
  UPOSlibClaim = 4,
  UPOSlibGetClaimed = 5,
  UPOSlibRelease = 6,
  UPOSlibSetDeviceEnabled = 7,
  UPOSlibGetDeviceEnabled = 8,
  UPOSlibGetState = 9,
  UPOSlibSetAsyncMode = 10,
  UPOSlibGetAsyncMode = 11,
  UPOSlibDirectIO = 12,
  UPOSlibOpenDrawer = 13,
  UPOSlibOpened = 14,
  UPOSlibWaitForDrawerClose = 15
};
bool CmdTypeCashDrawer_IsValid(int value);
const CmdTypeCashDrawer CmdTypeCashDrawer_MIN = UPOSlibInit;
const CmdTypeCashDrawer CmdTypeCashDrawer_MAX = UPOSlibWaitForDrawerClose;
const int CmdTypeCashDrawer_ARRAYSIZE = CmdTypeCashDrawer_MAX + 1;

const ::google::protobuf::EnumDescriptor* CmdTypeCashDrawer_descriptor();
inline const ::std::string& CmdTypeCashDrawer_Name(CmdTypeCashDrawer value) {
  return ::google::protobuf::internal::NameOfEnum(
    CmdTypeCashDrawer_descriptor(), value);
}
inline bool CmdTypeCashDrawer_Parse(
    const ::std::string& name, CmdTypeCashDrawer* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CmdTypeCashDrawer>(
    CmdTypeCashDrawer_descriptor(), name, value);
}
// ===================================================================

class Params : public ::google::protobuf::Message {
 public:
  Params();
  virtual ~Params();

  Params(const Params& from);

  inline Params& operator=(const Params& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Params& default_instance();

  void Swap(Params* other);

  // implements Message ----------------------------------------------

  Params* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Params& from);
  void MergeFrom(const Params& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .JposcashdrawerZMQ.CmdTypeCashDrawer cmd = 1;
  inline bool has_cmd() const;
  inline void clear_cmd();
  static const int kCmdFieldNumber = 1;
  inline ::JposcashdrawerZMQ::CmdTypeCashDrawer cmd() const;
  inline void set_cmd(::JposcashdrawerZMQ::CmdTypeCashDrawer value);

  // optional uint32 instHdl = 2;
  inline bool has_insthdl() const;
  inline void clear_insthdl();
  static const int kInstHdlFieldNumber = 2;
  inline ::google::protobuf::uint32 insthdl() const;
  inline void set_insthdl(::google::protobuf::uint32 value);

  // repeated int32 int32Param = 3 [packed = true];
  inline int int32param_size() const;
  inline void clear_int32param();
  static const int kInt32ParamFieldNumber = 3;
  inline ::google::protobuf::int32 int32param(int index) const;
  inline void set_int32param(int index, ::google::protobuf::int32 value);
  inline void add_int32param(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      int32param() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_int32param();

  // repeated uint32 uint32Param = 4 [packed = true];
  inline int uint32param_size() const;
  inline void clear_uint32param();
  static const int kUint32ParamFieldNumber = 4;
  inline ::google::protobuf::uint32 uint32param(int index) const;
  inline void set_uint32param(int index, ::google::protobuf::uint32 value);
  inline void add_uint32param(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      uint32param() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_uint32param();

  // repeated uint64 uint64Param = 5 [packed = true];
  inline int uint64param_size() const;
  inline void clear_uint64param();
  static const int kUint64ParamFieldNumber = 5;
  inline ::google::protobuf::uint64 uint64param(int index) const;
  inline void set_uint64param(int index, ::google::protobuf::uint64 value);
  inline void add_uint64param(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      uint64param() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_uint64param();

  // repeated bool boolParam = 6;
  inline int boolparam_size() const;
  inline void clear_boolparam();
  static const int kBoolParamFieldNumber = 6;
  inline bool boolparam(int index) const;
  inline void set_boolparam(int index, bool value);
  inline void add_boolparam(bool value);
  inline const ::google::protobuf::RepeatedField< bool >&
      boolparam() const;
  inline ::google::protobuf::RepeatedField< bool >*
      mutable_boolparam();

  // repeated string strParam = 7;
  inline int strparam_size() const;
  inline void clear_strparam();
  static const int kStrParamFieldNumber = 7;
  inline const ::std::string& strparam(int index) const;
  inline ::std::string* mutable_strparam(int index);
  inline void set_strparam(int index, const ::std::string& value);
  inline void set_strparam(int index, const char* value);
  inline void set_strparam(int index, const char* value, size_t size);
  inline ::std::string* add_strparam();
  inline void add_strparam(const ::std::string& value);
  inline void add_strparam(const char* value);
  inline void add_strparam(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& strparam() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_strparam();

  // optional bytes buffer = 8;
  inline bool has_buffer() const;
  inline void clear_buffer();
  static const int kBufferFieldNumber = 8;
  inline const ::std::string& buffer() const;
  inline void set_buffer(const ::std::string& value);
  inline void set_buffer(const char* value);
  inline void set_buffer(const void* value, size_t size);
  inline ::std::string* mutable_buffer();
  inline ::std::string* release_buffer();
  inline void set_allocated_buffer(::std::string* buffer);

  // optional string errorText = 9;
  inline bool has_errortext() const;
  inline void clear_errortext();
  static const int kErrorTextFieldNumber = 9;
  inline const ::std::string& errortext() const;
  inline void set_errortext(const ::std::string& value);
  inline void set_errortext(const char* value);
  inline void set_errortext(const char* value, size_t size);
  inline ::std::string* mutable_errortext();
  inline ::std::string* release_errortext();
  inline void set_allocated_errortext(::std::string* errortext);

  // optional int32 errorCode = 10;
  inline bool has_errorcode() const;
  inline void clear_errorcode();
  static const int kErrorCodeFieldNumber = 10;
  inline ::google::protobuf::int32 errorcode() const;
  inline void set_errorcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:JposcashdrawerZMQ.Params)
 private:
  inline void set_has_cmd();
  inline void clear_has_cmd();
  inline void set_has_insthdl();
  inline void clear_has_insthdl();
  inline void set_has_buffer();
  inline void clear_has_buffer();
  inline void set_has_errortext();
  inline void clear_has_errortext();
  inline void set_has_errorcode();
  inline void clear_has_errorcode();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int cmd_;
  ::google::protobuf::uint32 insthdl_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > int32param_;
  mutable int _int32param_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > uint32param_;
  mutable int _uint32param_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > uint64param_;
  mutable int _uint64param_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > boolparam_;
  ::google::protobuf::RepeatedPtrField< ::std::string> strparam_;
  ::std::string* buffer_;
  ::std::string* errortext_;
  ::google::protobuf::int32 errorcode_;
  friend void  protobuf_AddDesc_uposcashdrawer_2eproto();
  friend void protobuf_AssignDesc_uposcashdrawer_2eproto();
  friend void protobuf_ShutdownFile_uposcashdrawer_2eproto();

  void InitAsDefaultInstance();
  static Params* default_instance_;
};
// ===================================================================


// ===================================================================

// Params

// optional .JposcashdrawerZMQ.CmdTypeCashDrawer cmd = 1;
inline bool Params::has_cmd() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Params::set_has_cmd() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Params::clear_has_cmd() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Params::clear_cmd() {
  cmd_ = 0;
  clear_has_cmd();
}
inline ::JposcashdrawerZMQ::CmdTypeCashDrawer Params::cmd() const {
  // @@protoc_insertion_point(field_get:JposcashdrawerZMQ.Params.cmd)
  return static_cast< ::JposcashdrawerZMQ::CmdTypeCashDrawer >(cmd_);
}
inline void Params::set_cmd(::JposcashdrawerZMQ::CmdTypeCashDrawer value) {
  assert(::JposcashdrawerZMQ::CmdTypeCashDrawer_IsValid(value));
  set_has_cmd();
  cmd_ = value;
  // @@protoc_insertion_point(field_set:JposcashdrawerZMQ.Params.cmd)
}

// optional uint32 instHdl = 2;
inline bool Params::has_insthdl() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Params::set_has_insthdl() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Params::clear_has_insthdl() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Params::clear_insthdl() {
  insthdl_ = 0u;
  clear_has_insthdl();
}
inline ::google::protobuf::uint32 Params::insthdl() const {
  // @@protoc_insertion_point(field_get:JposcashdrawerZMQ.Params.instHdl)
  return insthdl_;
}
inline void Params::set_insthdl(::google::protobuf::uint32 value) {
  set_has_insthdl();
  insthdl_ = value;
  // @@protoc_insertion_point(field_set:JposcashdrawerZMQ.Params.instHdl)
}

// repeated int32 int32Param = 3 [packed = true];
inline int Params::int32param_size() const {
  return int32param_.size();
}
inline void Params::clear_int32param() {
  int32param_.Clear();
}
inline ::google::protobuf::int32 Params::int32param(int index) const {
  // @@protoc_insertion_point(field_get:JposcashdrawerZMQ.Params.int32Param)
  return int32param_.Get(index);
}
inline void Params::set_int32param(int index, ::google::protobuf::int32 value) {
  int32param_.Set(index, value);
  // @@protoc_insertion_point(field_set:JposcashdrawerZMQ.Params.int32Param)
}
inline void Params::add_int32param(::google::protobuf::int32 value) {
  int32param_.Add(value);
  // @@protoc_insertion_point(field_add:JposcashdrawerZMQ.Params.int32Param)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Params::int32param() const {
  // @@protoc_insertion_point(field_list:JposcashdrawerZMQ.Params.int32Param)
  return int32param_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Params::mutable_int32param() {
  // @@protoc_insertion_point(field_mutable_list:JposcashdrawerZMQ.Params.int32Param)
  return &int32param_;
}

// repeated uint32 uint32Param = 4 [packed = true];
inline int Params::uint32param_size() const {
  return uint32param_.size();
}
inline void Params::clear_uint32param() {
  uint32param_.Clear();
}
inline ::google::protobuf::uint32 Params::uint32param(int index) const {
  // @@protoc_insertion_point(field_get:JposcashdrawerZMQ.Params.uint32Param)
  return uint32param_.Get(index);
}
inline void Params::set_uint32param(int index, ::google::protobuf::uint32 value) {
  uint32param_.Set(index, value);
  // @@protoc_insertion_point(field_set:JposcashdrawerZMQ.Params.uint32Param)
}
inline void Params::add_uint32param(::google::protobuf::uint32 value) {
  uint32param_.Add(value);
  // @@protoc_insertion_point(field_add:JposcashdrawerZMQ.Params.uint32Param)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
Params::uint32param() const {
  // @@protoc_insertion_point(field_list:JposcashdrawerZMQ.Params.uint32Param)
  return uint32param_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
Params::mutable_uint32param() {
  // @@protoc_insertion_point(field_mutable_list:JposcashdrawerZMQ.Params.uint32Param)
  return &uint32param_;
}

// repeated uint64 uint64Param = 5 [packed = true];
inline int Params::uint64param_size() const {
  return uint64param_.size();
}
inline void Params::clear_uint64param() {
  uint64param_.Clear();
}
inline ::google::protobuf::uint64 Params::uint64param(int index) const {
  // @@protoc_insertion_point(field_get:JposcashdrawerZMQ.Params.uint64Param)
  return uint64param_.Get(index);
}
inline void Params::set_uint64param(int index, ::google::protobuf::uint64 value) {
  uint64param_.Set(index, value);
  // @@protoc_insertion_point(field_set:JposcashdrawerZMQ.Params.uint64Param)
}
inline void Params::add_uint64param(::google::protobuf::uint64 value) {
  uint64param_.Add(value);
  // @@protoc_insertion_point(field_add:JposcashdrawerZMQ.Params.uint64Param)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
Params::uint64param() const {
  // @@protoc_insertion_point(field_list:JposcashdrawerZMQ.Params.uint64Param)
  return uint64param_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
Params::mutable_uint64param() {
  // @@protoc_insertion_point(field_mutable_list:JposcashdrawerZMQ.Params.uint64Param)
  return &uint64param_;
}

// repeated bool boolParam = 6;
inline int Params::boolparam_size() const {
  return boolparam_.size();
}
inline void Params::clear_boolparam() {
  boolparam_.Clear();
}
inline bool Params::boolparam(int index) const {
  // @@protoc_insertion_point(field_get:JposcashdrawerZMQ.Params.boolParam)
  return boolparam_.Get(index);
}
inline void Params::set_boolparam(int index, bool value) {
  boolparam_.Set(index, value);
  // @@protoc_insertion_point(field_set:JposcashdrawerZMQ.Params.boolParam)
}
inline void Params::add_boolparam(bool value) {
  boolparam_.Add(value);
  // @@protoc_insertion_point(field_add:JposcashdrawerZMQ.Params.boolParam)
}
inline const ::google::protobuf::RepeatedField< bool >&
Params::boolparam() const {
  // @@protoc_insertion_point(field_list:JposcashdrawerZMQ.Params.boolParam)
  return boolparam_;
}
inline ::google::protobuf::RepeatedField< bool >*
Params::mutable_boolparam() {
  // @@protoc_insertion_point(field_mutable_list:JposcashdrawerZMQ.Params.boolParam)
  return &boolparam_;
}

// repeated string strParam = 7;
inline int Params::strparam_size() const {
  return strparam_.size();
}
inline void Params::clear_strparam() {
  strparam_.Clear();
}
inline const ::std::string& Params::strparam(int index) const {
  // @@protoc_insertion_point(field_get:JposcashdrawerZMQ.Params.strParam)
  return strparam_.Get(index);
}
inline ::std::string* Params::mutable_strparam(int index) {
  // @@protoc_insertion_point(field_mutable:JposcashdrawerZMQ.Params.strParam)
  return strparam_.Mutable(index);
}
inline void Params::set_strparam(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:JposcashdrawerZMQ.Params.strParam)
  strparam_.Mutable(index)->assign(value);
}
inline void Params::set_strparam(int index, const char* value) {
  strparam_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:JposcashdrawerZMQ.Params.strParam)
}
inline void Params::set_strparam(int index, const char* value, size_t size) {
  strparam_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:JposcashdrawerZMQ.Params.strParam)
}
inline ::std::string* Params::add_strparam() {
  return strparam_.Add();
}
inline void Params::add_strparam(const ::std::string& value) {
  strparam_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:JposcashdrawerZMQ.Params.strParam)
}
inline void Params::add_strparam(const char* value) {
  strparam_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:JposcashdrawerZMQ.Params.strParam)
}
inline void Params::add_strparam(const char* value, size_t size) {
  strparam_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:JposcashdrawerZMQ.Params.strParam)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Params::strparam() const {
  // @@protoc_insertion_point(field_list:JposcashdrawerZMQ.Params.strParam)
  return strparam_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Params::mutable_strparam() {
  // @@protoc_insertion_point(field_mutable_list:JposcashdrawerZMQ.Params.strParam)
  return &strparam_;
}

// optional bytes buffer = 8;
inline bool Params::has_buffer() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Params::set_has_buffer() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Params::clear_has_buffer() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Params::clear_buffer() {
  if (buffer_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    buffer_->clear();
  }
  clear_has_buffer();
}
inline const ::std::string& Params::buffer() const {
  // @@protoc_insertion_point(field_get:JposcashdrawerZMQ.Params.buffer)
  return *buffer_;
}
inline void Params::set_buffer(const ::std::string& value) {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    buffer_ = new ::std::string;
  }
  buffer_->assign(value);
  // @@protoc_insertion_point(field_set:JposcashdrawerZMQ.Params.buffer)
}
inline void Params::set_buffer(const char* value) {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    buffer_ = new ::std::string;
  }
  buffer_->assign(value);
  // @@protoc_insertion_point(field_set_char:JposcashdrawerZMQ.Params.buffer)
}
inline void Params::set_buffer(const void* value, size_t size) {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    buffer_ = new ::std::string;
  }
  buffer_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:JposcashdrawerZMQ.Params.buffer)
}
inline ::std::string* Params::mutable_buffer() {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    buffer_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:JposcashdrawerZMQ.Params.buffer)
  return buffer_;
}
inline ::std::string* Params::release_buffer() {
  clear_has_buffer();
  if (buffer_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = buffer_;
    buffer_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Params::set_allocated_buffer(::std::string* buffer) {
  if (buffer_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete buffer_;
  }
  if (buffer) {
    set_has_buffer();
    buffer_ = buffer;
  } else {
    clear_has_buffer();
    buffer_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:JposcashdrawerZMQ.Params.buffer)
}

// optional string errorText = 9;
inline bool Params::has_errortext() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Params::set_has_errortext() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Params::clear_has_errortext() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Params::clear_errortext() {
  if (errortext_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    errortext_->clear();
  }
  clear_has_errortext();
}
inline const ::std::string& Params::errortext() const {
  // @@protoc_insertion_point(field_get:JposcashdrawerZMQ.Params.errorText)
  return *errortext_;
}
inline void Params::set_errortext(const ::std::string& value) {
  set_has_errortext();
  if (errortext_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    errortext_ = new ::std::string;
  }
  errortext_->assign(value);
  // @@protoc_insertion_point(field_set:JposcashdrawerZMQ.Params.errorText)
}
inline void Params::set_errortext(const char* value) {
  set_has_errortext();
  if (errortext_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    errortext_ = new ::std::string;
  }
  errortext_->assign(value);
  // @@protoc_insertion_point(field_set_char:JposcashdrawerZMQ.Params.errorText)
}
inline void Params::set_errortext(const char* value, size_t size) {
  set_has_errortext();
  if (errortext_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    errortext_ = new ::std::string;
  }
  errortext_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:JposcashdrawerZMQ.Params.errorText)
}
inline ::std::string* Params::mutable_errortext() {
  set_has_errortext();
  if (errortext_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    errortext_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:JposcashdrawerZMQ.Params.errorText)
  return errortext_;
}
inline ::std::string* Params::release_errortext() {
  clear_has_errortext();
  if (errortext_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = errortext_;
    errortext_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Params::set_allocated_errortext(::std::string* errortext) {
  if (errortext_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete errortext_;
  }
  if (errortext) {
    set_has_errortext();
    errortext_ = errortext;
  } else {
    clear_has_errortext();
    errortext_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:JposcashdrawerZMQ.Params.errorText)
}

// optional int32 errorCode = 10;
inline bool Params::has_errorcode() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Params::set_has_errorcode() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Params::clear_has_errorcode() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Params::clear_errorcode() {
  errorcode_ = 0;
  clear_has_errorcode();
}
inline ::google::protobuf::int32 Params::errorcode() const {
  // @@protoc_insertion_point(field_get:JposcashdrawerZMQ.Params.errorCode)
  return errorcode_;
}
inline void Params::set_errorcode(::google::protobuf::int32 value) {
  set_has_errorcode();
  errorcode_ = value;
  // @@protoc_insertion_point(field_set:JposcashdrawerZMQ.Params.errorCode)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace JposcashdrawerZMQ

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::JposcashdrawerZMQ::CmdTypeCashDrawer> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::JposcashdrawerZMQ::CmdTypeCashDrawer>() {
  return ::JposcashdrawerZMQ::CmdTypeCashDrawer_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_uposcashdrawer_2eproto__INCLUDED
